name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUNNIG_GITHUB_CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests

    - name: Send Webhook if tests pass
      if: success()
      env:
        SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: |
        payload='{"status": "success", "nonce": "${{ steps.random-string.outputs.random }}"}'
        signature=$(echo -n $payload | openssl dgst -sha1 -hmac "$SECRET" | sed 's/^.* //')
        curl -X POST -H "Content-Type: application/json" -H "X-Hub-Signature: sha1=$signature" -d "$payload" https://webhook.amano.mydns.jp/deploy/linebot
